import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

// Path to the virtual ledger file generated by the Python script
const LEDGER_PATH = path.join(process.cwd(), 'scripts', 'virtual_ledger.json');

export async function GET() {
    try {
        if (!fs.existsSync(LEDGER_PATH)) {
            // Return default structure if file doesn't exist yet
            return NextResponse.json({
                capital_current_USDC: 10000.00,
                capital_initial_USDC: 10000.00,
                processed_market_ids: [],
                trades: []
            });
        }

        const fileContent = fs.readFileSync(LEDGER_PATH, 'utf-8');
        const ledger = JSON.parse(fileContent);

        return NextResponse.json(ledger);
    } catch (error) {
        console.error('Error reading virtual ledger:', error);
        return NextResponse.json(
            { error: 'Failed to read ledger data' },
            { status: 500 }
        );
    }
}
